// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkiwyamxdmiwpcgkaxfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZraXd5YW14ZG1pd3BjZ2theGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDUyNjIsImV4cCI6MjA2NjQyMTI2Mn0.sMpX_RrawO8fbV_OUbkae2QyZsh55tBZpthN5j7BsCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);